import Head from 'next/head';

import { Results } from '@/components/Results';
import products from '@/data/products.json';
import { Product } from '@/types/index';

type HomeProps = {
  products: Product[];
};

export default function Home({ products }: HomeProps) {
  return (
    <>
      <Head>
        <title>Mayoral DS</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Results products={products} />
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  return {
    props: { products },
  };
};
